-- HVAC & Energy Systems Wiki
-- Supabase 匿名开放问答区：建表、RLS 和 Realtime 配置
-- 执行位置：Supabase Dashboard -> SQL Editor
-- 说明：匿名登录用户在 Supabase 中使用 authenticated 角色；管理员治理通过 Dashboard 完成。

create extension if not exists pgcrypto;

create table if not exists public.community_questions (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(btrim(title)) between 4 and 160),
  content text not null check (char_length(btrim(content)) between 1 and 5000),
  author_id uuid references auth.users(id) on delete set null,
  status text not null default 'visible' check (status in ('visible', 'hidden', 'deleted', 'archived')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_answers (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.community_questions(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 5000),
  author_id uuid references auth.users(id) on delete set null,
  status text not null default 'visible' check (status in ('visible', 'hidden', 'deleted', 'archived')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_moderation_log (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('question', 'answer')),
  target_id uuid not null,
  action text not null check (action in ('hide', 'restore', 'delete', 'archive', 'note')),
  reason text,
  operator text not null default current_user,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists community_questions_created_at_idx
  on public.community_questions (created_at desc);

create index if not exists community_questions_status_idx
  on public.community_questions (status);

create index if not exists community_answers_question_created_at_idx
  on public.community_answers (question_id, created_at asc);

create index if not exists community_answers_status_idx
  on public.community_answers (status);

create or replace function public.set_community_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists community_questions_set_updated_at on public.community_questions;
create trigger community_questions_set_updated_at
before update on public.community_questions
for each row execute function public.set_community_updated_at();

drop trigger if exists community_answers_set_updated_at on public.community_answers;
create trigger community_answers_set_updated_at
before update on public.community_answers
for each row execute function public.set_community_updated_at();

create or replace function public.log_community_moderation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  moderation_action text;
  operator_name text;
begin
  if tg_op = 'DELETE' then
    moderation_action := 'delete';
  elsif old.status is distinct from new.status then
    moderation_action := case new.status
      when 'hidden' then 'hide'
      when 'visible' then 'restore'
      when 'deleted' then 'delete'
      when 'archived' then 'archive'
    end;
  else
    return new;
  end if;

  operator_name := coalesce(nullif(current_setting('request.jwt.claim.sub', true), ''), current_user);

  insert into public.community_moderation_log (target_type, target_id, action, operator)
  values (
    case when tg_table_name = 'community_questions' then 'question' else 'answer' end,
    case when tg_op = 'DELETE' then old.id else new.id end,
    moderation_action,
    operator_name
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists community_questions_log_moderation on public.community_questions;
create trigger community_questions_log_moderation
after update or delete on public.community_questions
for each row execute function public.log_community_moderation();

drop trigger if exists community_answers_log_moderation on public.community_answers;
create trigger community_answers_log_moderation
after update or delete on public.community_answers
for each row execute function public.log_community_moderation();

alter table public.community_questions enable row level security;
alter table public.community_answers enable row level security;
alter table public.community_moderation_log enable row level security;

drop policy if exists "Public can read visible questions" on public.community_questions;
create policy "Public can read visible questions"
on public.community_questions
for select
to authenticated
using (status = 'visible');

drop policy if exists "Authenticated users can create questions" on public.community_questions;
create policy "Authenticated users can create questions"
on public.community_questions
for insert
to authenticated
with check (author_id = (select auth.uid()) and status = 'visible');

drop policy if exists "Public can read visible answers" on public.community_answers;
create policy "Public can read visible answers"
on public.community_answers
for select
to authenticated
using (status = 'visible');

drop policy if exists "Authenticated users can create answers" on public.community_answers;
create policy "Authenticated users can create answers"
on public.community_answers
for insert
to authenticated
with check (
  author_id = (select auth.uid())
  and status = 'visible'
  and exists (
    select 1
    from public.community_questions q
    where q.id = question_id
      and q.status = 'visible'
  )
);

-- 不为普通用户开放治理日志访问，也不开放直接修改 status。
-- 管理员通过 Supabase Dashboard 的 Table Editor/SQL Editor 进行隐藏、恢复、删除和归档。

alter table public.community_questions replica identity full;
alter table public.community_answers replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.community_questions;
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.community_answers;
exception
  when duplicate_object then null;
end;
$$;
